services:
  - type: web
    name: mr-dmi-1
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m unittest test_engine test_identification test_api test_deployment && gunicorn --check-config app:app
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /healthz
