const assert = require('node:assert/strict');
const {extractIdentifiers} = require('./identification.js');
assert.deepEqual(extractIdentifiers('Medtronic\nModel: A2DR01\nSerial: 998877'), {makers:['Medtronic'],models:['A2DR01'],families:[],serials:['998877'],serialCandidates:[],udi:''});
assert.deepEqual(extractIdentifiers('Abbott Model: PM2272\nREF: 2088TC-52').models,['PM2272','2088TC-52']);
assert.equal(extractIdentifiers('Séjour 01234567890123').udi,'');
assert.equal(extractIdentifiers('(01)01234567890123(21)1234').udi,'01234567890123');
assert.equal(extractIdentifiers('taille 23 numéro série 12345').models.length,0);
assert.equal(extractIdentifiers('Medtronic Abbott Model: A2').makers.length,2);
console.log('6 local extraction checks passed');

const card=extractIdentifiers('Abbott Modèle TENDRIL STS\\nN° de série EEL414832\\nAbbott Modèle TENDRIL STS\\nN° de série EEM330008');
assert.deepEqual(card.models,['TENDRIL STS']);
assert.deepEqual(card.serials,['EEL414832','EEM330008']);
assert.deepEqual(extractIdentifiers('Omnipod Model: 5').makers,['Insulet']);
assert.deepEqual(extractIdentifiers('MEDel').makers,['MED-EL']);


assert.deepEqual(extractIdentifiers('Modèle\nli').models,[]);
assert.deepEqual(extractIdentifiers('N° de série\n|\nEEL414832').serialCandidates,['EEL414832']);

const {evaluateDmiWorkflow,dmiRoleTasks}=require('./identification.js');
const implant={maker:'Cochlear',model:'CI632',category:'cochlear',confirmed:true};
assert.equal(evaluateDmiWorkflow([implant],{field_t:3},true).blocked,false);
assert.match(evaluateDmiWorkflow([implant],{field_t:3},true).status,/incomplète/);
assert.equal(evaluateDmiWorkflow([implant],{field_t:.55},true).blocked,true);
assert.equal(evaluateDmiWorkflow([{...implant,confirmed:false}],{field_t:3},true).sources.length,0);
assert.equal(evaluateDmiWorkflow([{...implant,model:'CI999'}],{field_t:3},true).sources.length,0);
assert.ok(evaluateDmiWorkflow([implant],{},false).missing.some(x=>/Inventaire/.test(x)));
const generator={maker:'Abbott',model:'3660',category:'neuro',confirmed:true};
const lead={maker:'Abbott',model:'3186',category:'lead',length_cm:60,confirmed:true};
assert.equal(evaluateDmiWorkflow([generator],{field_t:1.5},true).sources.length,0);
assert.equal(evaluateDmiWorkflow([generator,{...lead,length_cm:90}],{field_t:1.5},true).sources.length,0);
assert.equal(evaluateDmiWorkflow([generator,lead],{field_t:3},true).blocked,true);
assert.equal(evaluateDmiWorkflow([generator,lead],{field_t:1.5,total_active_min:31},true).blocked,true);
assert.equal(evaluateDmiWorkflow([generator,lead],{field_t:1.5,total_active_min:30,wait_min:29},true).blocked,true);
assert.equal(evaluateDmiWorkflow([generator,lead,{...lead,category:'extension'}],{field_t:1.5},true).sources.length,0);
assert.equal(evaluateDmiWorkflow([{maker:'Insulet',model:'OMNIPOD 5',category:'pump',confirmed:true}],{},true).findings[0].status,'préparation requise');
assert.ok(dmiRoleTasks('secretary',[implant]).some(x=>/Transmettre/.test(x)));
assert.ok(dmiRoleTasks('prescriber',[implant]).some(x=>/indication/.test(x)));
console.log('16 contrôles de parcours, composants, sources et limites documentaires réussis');
const cardiac={maker:'Abbott',model:'PM2272',category:'cardiac',system:'1',confirmed:true};
const pacingLead={maker:'Abbott',model:'2088TC',length_cm:52,category:'lead',system:'1',confirmed:true};
const plan={field_t:1.5,mode:'normal',spatial_gradient_t_m:20,gradient_slew_t_m_s:180};
let cardiacResult=evaluateDmiWorkflow([pacingLead,cardiac],plan,true);
assert.equal(cardiacResult.sources.length,1);
assert.equal(cardiacResult.blocked,false);
assert.ok(!cardiacResult.missing.some(x=>/aucune condition exacte/.test(x)));
assert.match(cardiacResult.sources[0].document_version,/600159320/);
assert.equal(evaluateDmiWorkflow([cardiac,{...pacingLead,length_cm:65}],plan,true).sources.length,0);
assert.equal(evaluateDmiWorkflow([cardiac,{...pacingLead,system:'2'}],plan,true).sources.length,0);
assert.equal(evaluateDmiWorkflow([cardiac,{...pacingLead,confirmed:false}],plan,true).sources.length,0);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead,{...cardiac,model:'PM1272'}],plan,true).sources.length,0);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead],{...plan,field_t:.55},true).blocked,true);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead],{...plan,spatial_gradient_t_m:31},true).blocked,true);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead],{...plan,gradient_slew_t_m_s:201},true).blocked,true);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead],{...plan,mode:'first'},true).blocked,true);
const concurrent=evaluateDmiWorkflow([cardiac,pacingLead,{...generator,system:'2'},{...lead,system:'2'}],plan,true);
assert.equal(concurrent.sources.length,2);
assert.equal(evaluateDmiWorkflow([cardiac,pacingLead,{...pacingLead,maker:'Medtronic'}],plan,true).sources.length,0);
assert.deepEqual(extractIdentifiers('Abbott\nPM2272\n2088TC').models,['PM2272','2088TC']);
console.log('15 contrôles supplémentaires systèmes cardiaques et associations réussis');

assert.equal(evaluateDmiWorkflow([generator,lead,{...generator,model:'3662'}],{field_t:1.5},true).sources.length,0);

assert.ok(!dmiRoleTasks('technologist',[generator,lead]).some(x=>/Système cardiaque/.test(x)));
assert.ok(dmiRoleTasks('technologist',[lead]).some(x=>/Sonde ou électrode seule/.test(x)));

const technical={...plan,bore:'horizontal_cylindrical',nucleus:'hydrogen',position:'supine_arms_sides',implant_location:'pectoral',transmit_coil:'body'};
const verify=exam=>evaluateDmiWorkflow([cardiac,pacingLead],exam,true);
assert.ok(verify(plan).findings.some(x=>x.criterion==='Antenne RF émettrice'&&x.status==='inconnu'));
assert.equal(verify(technical).blocked,false);
for(const key of ['bore','nucleus','position','implant_location','transmit_coil'])assert.equal(verify({...technical,[key]:'other'}).blocked,true,key);
assert.equal(verify({...technical,field_t:3,transmit_coil:'local_head',rf_polarization:'cp'}).blocked,true);
assert.ok(verify({...technical,field_t:3}).findings.some(x=>x.criterion==='Polarisation RF'&&x.status==='inconnu'));
assert.equal(verify({...technical,field_t:3,rf_polarization:'other'}).blocked,true);
assert.equal(verify({...technical,field_t:3,rf_polarization:'cp'}).blocked,false);
assert.equal(verify({...technical,transmit_coil:'local_head',rf_polarization:'other'}).blocked,true);
assert.equal(verify({...technical,transmit_coil:'local_head',rf_polarization:'cp'}).blocked,false);
assert.ok(verify({...technical,field_t:.55}).missing.some(x=>/antenne RF non évaluée/.test(x)));
console.log('Contrôles RF, tunnel, position et informations manquantes réussis');
